
INSERT INTO lINGUA_ENTITY(ALLERGENI,AVVERTENZE,BENVENUTO,SIGLA,SOTTOTITOLO,URL_BANDIERA ) VALUES('**FOR INFO ON SUBSTANCES AND ALLERGENS, IT IS POSSIBLE TO CONSULT THE APPROPRIATE DOCUMENTATION PROVIDED UPON REQUEST BY THE STAFF**','**ALL OUR PRODUCT ARE FREEZED -28° ** COVER CHARGE €1 PER PERSON**','WELCOME TO','ingl','-COFFEE BAR - SALAD - SANDWICH - FRUIT EXTRACTS - FINE FRIED FOOD -','../images/great_britain.jpg');
INSERT INTO lINGUA_ENTITY(ALLERGENI,AVVERTENZE,BENVENUTO,SIGLA,SOTTOTITOLO,URL_BANDIERA ) VALUES('PER INFO SU SOSTANZE E ALLERGENI È POSSIBILE CONSULTARE L''APPOSITA DOCUMENTAZIONE FORNITA A RICHIESTA DAL PERSONALE**','**TUTTI I NOSTRI PRODOTTI SONO ABBATTUTI E CONSERVATI A -28° ** COSTO DEL COPERTO €1**','BENVENUTI DA','ita','- FRIGGITORIA ARTIGIANALE - INSALATE - CENTRIFUGHE - CAFFETTERIA -','../images/italy.png');
INSERT INTO lINGUA_ENTITY(ALLERGENI,AVVERTENZE,BENVENUTO,SIGLA,SOTTOTITOLO,URL_BANDIERA ) VALUES('**有关物质和过敏原的信息，您可以查阅工作人员根据要求提供的特别文件**','** 我们所有的产品均经过急速冷冻并储存在 -28° ** 成本 €1**','欢迎来到','cin','- 工匠油炸锅 - 沙拉 - 离心机 - 自助餐厅 -','../images/china.png');
INSERT INTO lINGUA_ENTITY(ALLERGENI,AVVERTENZE,BENVENUTO,SIGLA,SOTTOTITOLO,URL_BANDIERA ) VALUES('**POUR INFORMATIONS SUR LES SUBSTANCES ET LES ALLERGÈNES VOUS POUVEZ CONSULTER LA DOCUMENTATION SPÉCIALE FOURNIE SUR DEMANDE DU PERSONNEL**','**TOUS NOS PRODUITS SONT REFROIDIS ET CONSERVÉS À -28° ** COÛT DE COUVERURE 1 €**','BIENVENUE CHEZ','fra','- FRITEUSES ARTISANALES - SALADES - CENTRIFUGES - CAFÉ -','../images/france.png');
INSERT INTO lINGUA_ENTITY(ALLERGENI,AVVERTENZE,BENVENUTO,SIGLA,SOTTOTITOLO,URL_BANDIERA ) VALUES('**PARA INFORMACIÓN SOBRE SUSTANCIAS Y ALÉRGENOS PUEDE CONSULTAR LA DOCUMENTACIÓN ESPECIAL QUE SE PROPORCIONA A SOLICITUD POR EL PERSONAL**','**TODOS NUESTROS PRODUCTOS SON REFRIGERADOS Y ALMACENADOS A -28° ** CUBIERTO 1€**','BIENVENIDO A','spa','- FREIDORAS ARTESANALES - ENSALADAS - CENTRIFUGAS - CAFETERIA -','../images/spagna.webp');
INSERT INTO lINGUA_ENTITY(ALLERGENI,AVVERTENZE,BENVENUTO,SIGLA,SOTTOTITOLO,URL_BANDIERA ) VALUES('**INFORMATIONEN ZU STOFFEN UND ALLERGENEN KÖNNEN SIE AUF ANFRAGE DES PERSONALS IN DER SPEZIELLEN DOKUMENTATION EINSCHREIBEN**','**ALLE UNSERE PRODUKTE WERDEN SCHOCKGEKÜHLT UND BEI -28° GELAGERT ** DECKUNGSKOSTEN 1 €**','WILLKOMMEN BEI','ger','- HANDWERKLICHE FRITEUSEN – SALATE – ZENTRIFUGALEN – COFFEESHOP –','../images/germany.jpg');
INSERT INTO lINGUA_ENTITY(ALLERGENI,AVVERTENZE,BENVENUTO,SIGLA,SOTTOTITOLO,URL_BANDIERA ) VALUES('**物質とアレルゲンに関する情報については、スタッフのリクエストに応じて提供される特別文書を参照してください**','**当社の製品はすべて急速冷却され、-28°で保管されています。** カバーコスト €1**','ようこそ','jap','- 職人のフライヤー - サラダ - 遠心分離機 - コーヒーショップ -','../images/japan.jpg');
INSERT INTO lINGUA_ENTITY(ALLERGENI,AVVERTENZE,BENVENUTO,SIGLA,SOTTOTITOLO,URL_BANDIERA ) VALUES('**물질 및 알레르기 유발 물질에 대한 정보는 직원의 요청 시 제공되는 특별 문서를 참조할 수 있습니다**','**우리의 모든 제품은 급속 냉각되어 -28°에서 보관됩니다. ** 커버 비용 €1**','환영합니다','kor','- 장인 튀김기 - 샐러드 - 원심분리기 - 커피숍 -','../images/korea.png');
INSERT INTO lINGUA_ENTITY(ALLERGENI,AVVERTENZE,BENVENUTO,SIGLA,SOTTOTITOLO,URL_BANDIERA ) VALUES('**VOOR INFORMATIE OVER STOFFEN EN ALLERGENEN KUNT U DE SPECIALE DOCUMENTATIE RAADPLEGEN DIE OP VERZOEK DOOR HET PERSONEEL WORDT VERSTREKT**','**AL ONZE PRODUCTEN WORDEN BLAASTGEKOELD EN OPGESLAGEN BIJ -28° ** DEKKINGSKOSTEN € 1**','WELKOM BIJ','neth','- AMBACHTELIJKE FRITEUSES - SALADES - CENTRIFUGAALEN - KOFFIESHOP -','../images/netherland.webp');
INSERT INTO lINGUA_ENTITY(ALLERGENI,AVVERTENZE,BENVENUTO,SIGLA,SOTTOTITOLO,URL_BANDIERA ) VALUES('**PARA INFORMAÇÕES SOBRE SUBSTÂNCIAS E ALERGÉNIOS PODE CONSULTAR A DOCUMENTAÇÃO ESPECIAL FORNECIDA MEDIANTE PEDIDO DO PESSOAL**','**TODOS OS NOSSOS PRODUTOS SÃO REFRIGERADOS E ARMAZENADOS A -28° ** CUSTO DE COBERTURA 1€**','BEM-VINDO A','port','- FRITADEIRAS ARTESANAIS - SALADAS - CENTRÍFUGAS - CAFETEIRA -','../images/portugal.png');
INSERT INTO lINGUA_ENTITY(ALLERGENI,AVVERTENZE,BENVENUTO,SIGLA,SOTTOTITOLO,URL_BANDIERA ) VALUES('**ДЛЯ ИНФОРМАЦИИ О ВЕЩЕСТВАХ И АЛЛЕРГЕНАХ ВЫ МОЖЕТЕ СОДЕРЖАТЬ СПЕЦИАЛЬНУЮ ДОКУМЕНТАЦИЮ, ПРЕДОСТАВЛЯЕМУЮ ПО ЗАПРОСУ ПЕРСОНАЛА**','**ВСЕ НАШИ ПРОДУКТЫ ПРОДОЛЖАЮТСЯ ШОКОВОГО ОХЛАЖДЕНИЯ И ХРАНЯТСЯ ПРИ -28° ** СТОИМОСТЬ 1 ЕВРО**','ДОБРО ПОЖАЛОВАТЬ В','rush','- ARTISAN ФРИТЮРНИЦЫ - САЛАТЫ - ЦЕНТРОБЕГИ - КОФЕ МАГАЗИН -','../images/russian.png');
INSERT INTO lINGUA_ENTITY(ALLERGENI,AVVERTENZE,BENVENUTO,SIGLA,SOTTOTITOLO,URL_BANDIERA ) VALUES('**للحصول على معلومات حول المواد والمواد المسببة للحساسية، يمكنك الرجوع إلى الوثائق الخاصة المقدمة بناءً على طلب الموظفين','** جميع منتجاتنا يتم تبريدها وتخزينها في درجة حرارة -28 درجة ** تكلفة التغطية 1 يورو **',' مرحبا بك في','arab','- مقالي حرفية - السلطات - أجهزة الطرد المركزي - مقهى -","مرحبًا بك في','../images/arabo.png');

/*
 * 
 */


INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€2,80','','','../images/piatti/SuppliArtigianale.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€4,00','','','../images/piatti/FilettoDiBaccala.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€3,80','','','../images/piatti/MozzarellaInCarrozza.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€3,80','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€2,80','','','../images/piatti/Crocchetta.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€10,50','','','../images/piatti/VerdureInPastella.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€10,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€10,00','','','../images/piatti/NuggetsEChips.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€3,50','€5,00','','../images/piatti/PatatineStick.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€7,50(8pz)','€10,00(12pz)','','../images/piatti/MixMiniSuppli.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€10,00','€13,50','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€10,00','€13,50','','../images/piatti/CartoccioMoscardini.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€10,00','€14,00','','../images/piatti/CartoccioAlicette.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€9,00','€12,00','','../images/piatti/FishEChips.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€14,50','€19,50','','../images/piatti/GranMistoDiPesce.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€13,00','','','../images/piatti/PastaAmatriciana.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€14,00','','','../images/piatti/PastaAlRagu.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€18,00','','','../images/piatti/PastaSeefood.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€16,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€14,50','','','../images/piatti/PolpetteAlSugo.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€14,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€12,00','','','../images/piatti/Zuppa.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€13,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€13,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€13,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€17,00','','','../images/piatti/MenuPortofino.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€13,50','','','../images/piatti/MenuFrascati.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€13,50','','','../images/piatti/MenuVegetariano.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€10,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€15,00','','','../images/piatti/MenuDegustazioni.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€18,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€9,00','','','../images/piatti/InsalataGreen.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€9,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€9,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€12,50','','','../images/piatti/InsalataTonno.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€12,50','','','../images/piatti/InsalataSalmone.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€12,50','','','../images/piatti/InsalataCaesar.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€12,50','','','../images/piatti/InsalaraPier39.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€7,00','','','../images/piatti/PaninoClassico.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€7,00','','','../images/piatti/PaninoRustico.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€7,00','','','../images/piatti/PaninoCaprese.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€7,00','','','../images/piatti/PaninoCotoletta.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€7,50','','','../images/piatti/PaninoBresaola.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€7,50','','','../images/piatti/PaninoTacchino.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€7,50','','','../images/piatti/PaninoContadino.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€8,00','','','../images/piatti/PaninoNorvegese.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€8,00','','','../images/piatti/PaninoAmericano.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€8,00','','','../images/piatti/PaninoAmericanoVeg.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€6,50','','','../images/piatti/PaninoPizzaEMortazza.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,00','','','../images/piatti/PaninoToast.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€11,00','€18,50','','../images/piatti/Tagliere.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€6,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€6,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€6,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€6,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€6,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€4,00','€6,00','','../images/piatti/Spremuta.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,00','€7,00','','../images/piatti/Yogurt.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,00','€7,00','','../images/piatti/Macedonia.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,50','€8,00','',''); 
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,50','€8,00','',''); 
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,50','€8,00','',''); 
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,50','€8,00','',''); 
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,50','€8,00','',''); 
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,50','€8,00','',''); 
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,50','€8,00','',''); 
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€6,00','€24,00','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('','€13,00','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€6,00','€24,00','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€6,00','€24,00','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€6,50','€26,00','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€6,00','€13,00','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€6,50','€26,00','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€7,00','€29,00','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,00','€21,00','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€7,00','€28,00','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('','€13,00','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€7,00','€28,00','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€7,00','€28,00','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€8,00','€38,00','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€4,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€4,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€4,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€4,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,90','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€2,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€4,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€3,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€3,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€3,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€3,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€3,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€3,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€3,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€6,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€7,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€5,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€1,50','€2,50','','../images/piatti/Espresso.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€1,70','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€2,50','€3,50','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€2,20','€3,50','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€2,50','','','../images/piatti/The.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€3,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€2,00','€3,00','','../images/piatti/Cappuccino.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€2,20','€3,50','','../images/piatti/Caffellatte.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€2,20','','','../images/piatti/Marocchino.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€2,00','€2,60','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€2,50','€3,10','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€3,50','','','../images/piatti/Cioccolata.jpg');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€1,50','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€2,90','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€3,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€3,00','','','');
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€3,50','','','');
/*123*/
/*gnocchi in italiano*/
INSERT INTO MENU_ENTITY(PREZZO,PREZZO_DUE,FILTRO,URL) VALUES('€13,00','','','');


/*inglese*/
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Our Classies','','1');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Our Paper Cones','','2');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Fish paper cones','','3');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Roman dishes','','4');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Soup of the Day','','5');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('grandma''s goodies','','6');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Fretto''s Menù','','7');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Salads 100% Vegan','From the farmer ...fresh and genuine','8');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('The Chef''s Salads','From the farmer ...fresh and genuine','9');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('The Ciabatta Romana','The tips of the gourmet grocer','10');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Sandwich Light','The tips of the gourmet grocer','11');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Sandiwich gourmet(10min)','The tips of the gourmet grocer','12');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Simple... but of gret value','The tips of the gourmet grocer','13');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Selection of cold cuts and cheese','','14');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Dessert(gluten free)','','15');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Fresh fruit juice','','16');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Yogurt Parfait with fruits and granola','','17');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Seasonal fruit salad','','18');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Juice Extracts','Completely NATURAL... only fruit and fresh vegetables with no added sugar and ice ','19');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Our Winery','','20');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Beer','','21');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Drinks','','22');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Spirits','','23');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Cocktail','','24');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Cafè Hot Drinks','','25');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('Sweets','','26');

/*1	1		Our Classies
2	2		Our Paper Cones
3	3		Fish paper cones
4	4		Roman dishes
5	5		Soup of the Day
6	6		grandma's goodies
7	7		Fretto's Menù
8	8	From the farmer ...fresh and genuine	Salads 100% Vegan
9	9	From the farmer ...fresh and genuine	The Chef's Salads
10	10	The tips of the gourmet grocer	The Ciabatta Romana
11	11	The tips of the gourmet grocer	Sandwich Light
12	12	The tips of the gourmet grocer	Sandiwich gourmet(10min)
13	13	The tips of the gourmet grocer	Simple... but of gret value
14	14		Selection of cold cuts and cheese
15	15		Dessert
16	16		Fresh fruit juice
17	17		Yogurt Parfait with fruits and granola
18	18		Seasonal fruit salad
19	19	Completely NATURAL... only fruit and fresh vegetables with no added sugar and ice 	Juice Extracts
20	20		Our Winery
21	21		Beer
22	22		Drinks
23	23		Spirits
24	24		Cocktail
25	25		Cafè Hot Drinks
26	26		Sweets
*/



INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('1','1','1','','','Homemade Supplì','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('1','1','2','','','Codifish buttered fillet','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('1','1','3','','','Mozzarella in Carozza','(with anchonives or speck)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('1','1','4','','','Arancini from Sicily','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('1','1','5','','','Potato croquettes','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('2','1','6','','','Deep fried battered vegetables','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('2','1','7','','','Chicken cutlet & chips','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('2','1','8','','','Chicken nuggets & chips','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('2','1','9','Medium','Large','Chips or French fries','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('2','1','10','Medium','Large','Mix of mini-Supplì','(Classic,Amatriciana sauce,cheese & pepper)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('3','1','11','Medium','Large','Deep fried calamari','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('3','1','12','Medium','Large','Deep fried moscardini','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('3','1','13','Medium','Large','Filet of anchovies','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('3','1','14','Medium','Large','Fish & chips','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('3','1','15','Medium','Large','Gran mix','(Calamari,moscardini,anchovies,paranza,prawn)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('4','1','16','','','Pasta','(Carbonara,amatriciana,cacio & pepe)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('4','1','17','','','Pasta with bolognese','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('4','1','18','','','Pasta with seadfood','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('4','1','19','','','Pasta with meatballs','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('4','1','20','','','Meatnalls in sauce','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('4','1','21','','','Roast beef','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('5','1','22','','','Soup of the Day','Served with two mearballs or veggieballs and spicy fried bread');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('6','1','23','','','Lasagna with bolognese sauce','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('6','1','24','','','Lasagna with vegetables','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('6','1','25','','','Eggplant parmigiana','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('7','1','26','','','Portofino','(Calamari served in peper cone + battered codifish + glass of white wine)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('7','1','27','','','Frascati','(Mix of mini-Supplì + Mozzarella in carozza + beer 300ml)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('7','1','28','','','Vagetarian','(Potato croquette + deep fried battered vegetables + soft drink)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('7','1','29','','','Pic Nic','(Breaded chicken + french fries + soft drink)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('7','1','30','','','Tasting traditional recipes menù','(Supplì + codifish buttered fillet + Mozzarella in Carozza + arancini + croquette)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('7','1','31','','','Tasting traditional recipes menù with Beer','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('8','1','32','','','Green','(Mixed salad with carrot, fennet, tomato and chickpeas)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('8','1','33','','','Splet with Vegetables','(Fresh and light,spelt with seasonal vegetables)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('8','1','34','','','Cous cous','(Strean coocked semolina with fresh seasonal vegetables)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('9','1','35','','','Tuna salad','(Green sald and red radish with tuna in olive oil, artichokes, black olives and tomato)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('9','1','36','','','Salmon and avocado salad','(Green sald with crispy bread chicked bites,parmigiano cheese and fried bread, dressed with origianl Ceaser souce)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('9','1','37','','','Cesar Salad','(Mixed salad with crispy breaded chicken bites,parmigiano cheese and fried bread,dressed with original Ceasar souce)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('9','1','38','','','Pier 39','(Green sald and red radish with with king prawns, grapefruit, fennel and cherry tomatoes)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('10','1','39','','','Classica','(Raw ham with Mozzarella cheese and dried tomatoes)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('10','1','40','','','Rustica','(Raw ham with Mozzarella cheese dressed with black olives cream)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('10','1','41','','','Caprese','(Tomato and Mozzarella cheese on lettuce bed,dressed with ''Pesto'' sauce)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('10','1','42','','','Cotoletta','(Tender chicken cutlet with mayo on tomato and lettuce bed)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('11','1','43','','','Bresaola','(Whaole grain bread with ''Bresaola'',rocket and Parmigiano cheese)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('11','1','44','','','Tacchino','(Flat bread with roasted turkey,fresh cream tomato)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('11','1','45','','','Farmer''s sandwich','(Whaole grain bread with grilled seasonal vegetables and ''Pecorino'' cheese)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('12','1','46','','','Norvegese','(Bagel with smoked norwegian salmon,cheese cream,lime,pink pepper)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('12','1','47','','','American Style sandwich','(Meatballs on a lettuce and tomato bed dressed with ''Green Sauce'')');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('12','1','48','','','Americano Veg','(Eggplant and smocked Mozzarella balls on a lattuce and tomato bed with mayo)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('13','1','49','','','Pizza & ''Mortazza'' ','(the oven focaccia with ''Mortadella'' dressed with pistacchio cream)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('13','1','50','','','Toast','(Classic light toast with coocked ham and Mozzarella cheese)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('14','1','51','Medium','Large','Selection of cold cuts and cheese','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('15','1','52','','','Semifreddo Tiramisù','(Sweet Tiramisù cream with sponge cake soaked in Italian coffee)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('15','1','53','','','Chocolate Sufflè','(Dark chocolate sufflè with soft heat chocolate cream)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('15','1','54','','','Millefrolle Chocolate & Orange','(Crispy biscuits with hazeinuts between two soft mousse chocolate and orange)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('15','1','55','','','Cheesecake','(A crusty crushed cookies bottom layer with fresh cream cheese and a red fruit topping)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('15','1','56','','','Semifreddo with Pistachio','(Pistacchio mousse decorated with pistachio grain)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('16','1','57','Medium',' Large','Fresh fruit juice','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('17','1','58','Medium',' Large','Yogurt partfut with fruits and granola','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('18','1','59','Medium',' Large','Seasonal fruit salad','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('19','1','60','Medium',' Large','Classic','(Carrot,apple and ginger)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('19','1','61','Medium',' Large','Ace','(Orange,carrot,lemon[ginger])');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('19','1','62','Medium',' Large','Anti Water retention','(Pineapple,fennel and apple)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('19','1','63','Medium',' Large','Depurative','(Pineapple,fennel,lemon[ginger])');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('19','1','64','Medium',' Large','Vitamic','(Kiwi,apple,ginger)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('19','1','65','Medium',' Large','Fat burning','(Grapefruit,lemon,lime,pinapple and ginger)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('19','1','66','Medium',' Large','Pinzimonio','(Clery,carrot,tennel seasoned with oil,salt and pepper)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('20','1','67','Glass',' Bottle','Falanghina dei campi flegrei D.O.P','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('20','1','68','',' Bottle','Falanghina dei campi flegrei D.O.P(375ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('20','1','69','Glass',' Bottle','Vermentino Di Sardegna D.O.C','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('20','1','70','Glass',' Bottle','Pecorino I.G.T','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('20','1','71','Glass',' Bottle','Riflessi ''Circeo'' D.O.C','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('20','1','72','Glass',' Bottle','Chardonnay(375ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('20','1','73','Glass',' Bottle','Sauvignon Blanc ''Fumaio'' Castello Banfi','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('20','1','74','Glass',' Bottle','Gewurtraminer','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('20','1','75','Glass',' Bottle','Prosecco','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('20','1','76','Glass',' Bottle','Merlot in purezza D.O.C','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('20','1','77','',' Bottle','Merlot in purezza D.O.C(375ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('20','1','78','Glass',' Bottle','Cabernet Sauvignon ''Col di Sasso'' Castello Banfi','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('20','1','79','Glass',' Bottle','Chianti Classico D.O.C','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('20','1','80','Glass',' Bottle','Chianti Riserva D.O.C','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('21','1','81','','','Nastro Azzurro(330ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('21','1','82','','','Ichnusa(330ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('21','1','83','','','Menebrea(330ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('21','1','84','','','IPA(330ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('21','1','85','','','Heineken(330ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('21','1','86','','','Unfiltered Ichnusa(500ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('21','1','87','','','Peroni Riserva ''Red''(500ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('21','1','88','','','Messina with marine salt(500ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('21','1','89','','','Weiss clear','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('22','1','90','','','Water(500ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('22','1','91','','','Evian(1lt)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('22','1','92','','','Fanta Coca-Cola Sprite','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('22','1','93','','','Natural fruit juices','Peach,pineaaple,bluberry,ACE,pear)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('22','1','94','','','Ice Tea','(Lemon,peach)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('22','1','95','','','Chinotto','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('22','1','96','','','Tonica','(Classic and Lemon)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('22','1','97','','','Oransoda/Lemonsoda','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('22','1','98','','','Crodino/Campari Bitter','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('23','1','99','','','Amaro','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('23','1','100','','','Grappa','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('23','1','101','','','Rum/Whisky','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('23','1','102','','','Limoncello','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('23','1','103','','','Sambuca','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('24','1','104','','','Aperol/Campari Spritz','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('24','1','105','','','Alcoholic drink','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('24','1','106','','','Alcohol free drink','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('25','1','107','Classic','Large','Espresso','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('25','1','108','Classic','','Deka Coffee','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('25','1','109','Classic','Large','American Coffee','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('25','1','110','Classic','Large','Ice Coffee','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('25','1','111','Classic','','Tea','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('25','1','112','Classic','','Herbal tea','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('25','1','113','Classic','Large','Cappuccino','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('25','1','114','Classic','Large','Caffelatte','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('25','1','115','Classic','','''Marocchino''','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('25','1','116','Classic','Large','Barley','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('25','1','117','Classic','Large','Ginseng','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('25','1','118','Classic','','Hot Chocolate','(with cream + 0,50€)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('26','1','119','','','Homemade croissant','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('26','1','120','','','Granny''s donut','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('26','1','121','','','Tart with jam','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('26','1','122','','','Muffin','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('26','1','123','','','Cake of the day','');



/* italiano*/
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('I Classici','','1');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('I nostri Cartocci','','2');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Cartocci di Pesce','','3');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Piatti Romani','','4');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Zuppa del Giorno','','5');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('La golosita di Nonna','','6');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('I Nostri menù','','7');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Le Insalatone 100% Vegane','Direttamente dal contadino.. fresco e genuino','8');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Le Insalatone dello Chef','Direttamente dal contadino.. fresco e genuino','9');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('La Ciabatta Romana','I consigli del Salumiere gourmet','10');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Sandwich Light','I consigli del Salumiere gourmet','11');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Panini gourmet (10 min)','I consigli del Salumiere gourmet','12');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Semplici…ma di gran valore','I consigli del Salumiere gourmet','13');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('I Taglieri Salumi e Formaggi','','14');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Dessert monoporzione (gluten free)','','15');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Le spremute di frutta fresca','','16');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Yougurt con frutta e cereali','','17');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Macedonia di frutta di stagione','','18');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Centrifugati','Completamente NATURALE ... solo frutta e verdura fresca senza aggiunta di zucchero e ghiaccio','19');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('La nostra Cantina','','20');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Birra','','21');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Da Bere','','22');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Fine Pasto','','23');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Cocktail','','24');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Caffetteria','','25');
INSERT INTO STRUTTURA_ENTITY(SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES('Pasticceria','','26');


/*1	27		I Classici
2	28		I nostri Cartoci
3	29		Cartocci di Pesce
4	30		Piatti Romani
5	31		Zuppa del Giorno
6	32		La golosita di Nonna
7	33		I Nostri menù
8	34	Direttamente dal contadino.. fresco e genuino	Le Insalatone 100% Vegane
9	35	Direttamente dal contadino.. fresco e genuino	Le Insalatone dello Chef
10	36	I consigli del Salumiere gourmet	La Ciabatta Romana
11	37	I consigli del Salumiere gourmet	Sandwich Light
12	38	I consigli del Salumiere gourmet	Panini gourmet (10 min)
13	39	I consigli del Salumiere gourmet	Semplici…ma di gran valore
14	40		I Taglieri Salumi e Formaggi
15	41		Dessert monoporzione (gluten free)
16	42		Le spremute di frutta fresca
17	43		Yougurt con frutta e cereali
18	44		Macedonia di frutta di stagione
19	45	Completamente NATURALE ... solo frutta e verdura fresca senza aggiunta di zucchero e ghiaccio	Centrifugati
20	46		La nostra Cantina
21	47		Birra
22	48		Da Bere
23	49		Fine Pasto
24	50		Cocktail
25	51		Caffetteria
26	52		Pasticceria
*/


INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('27','2','1','','','Supplì','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('27','2','2','','','Filetto di Baccalà','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('27','2','3','','','Mozzarella in Carozza','(con alici o speck)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('27','2','4','','','Arancino Siciliano','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('27','2','5','','','Crocchetta di patate','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('28','2','6','','','Verdure in pastella','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('28','2','7','','','Cotoletta e patatine','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('28','2','8','','','Nuggets e patatine','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('28','2','9','Medium','Large','Patatine Chips o stick','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('28','2','10','Medium','Large','Mix of mini-Supplì','(Classico,amatriciana,cacio & pepe)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('29','2','11','Medium','Large','Calamari','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('29','2','12','Medium','Large','Moscardini','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('29','2','13','Medium','Large','Alicette','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('29','2','14','Medium','Large','Fish & chips','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('29','2','15','Medium','Large','Gran Misto di Pesce ','(Calamari, moscardini, alicette, paranza, gamberone)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('30','2','16','','','Pasta','(Carbonara,amatriciana,cacio&pepe)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('30','2','17','','','Pasta al ragù','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('30','2','124','','','Gnocchi','(Pomodoro,pesto,ragù)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('30','2','20','','','Polpette alla romana','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('30','2','21','','','Roast beef','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('31','2','22','','','Zuppa del Giorno ','Servita con 2 polpettine artigianali a scelta e crostini di pane fritto aromatizzati');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('32','2','23','','','Lasagna al Ragù','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('32','2','24','','','Lasagna vegetale','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('33','2','26','','','Portofino','(cartoccio di calamari + filetto di baccalà + calice di vino)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('33','2','27','','','Frascati','(cartoccio di mini supplì + mozzarella in carrozza + birra)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('33','2','28','','','Vegetariano','(crocchetta di patate + cartoccio verdure + bevanda)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('33','2','29','','','Pic Nic','(panino con cotoletta + patate fritte + bevanda)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('33','2','30','','','Degustazione fritti tradizionali ','(supplì + filetto di baccalà + mozzarella in carrozza + arancino + crocchetta)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('33','2','31','','','Degustazione + Birra','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('34','2','32','','','Green','(insalata mista con carote, finocchio, pomodoro e legumi)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('34','2','33','','','Farro con verdure','(fresco e leggero; farro con verdure di stagione)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('34','2','34','','','Cous cous','(granelli di semola al vapore con verdure di stagione)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('35','2','35','','','Insalata di Tonno','(insalata mista con tonno all’olio d’oliva, carciofini, olive e pomodori)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('35','2','36','','','Salmone e Avocado','(insalata mista con salmone affumicato, avocado e pomodoro, profumata con lime e pepe rosa)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('35','2','37','','','Caesar Salad','(insalata mista con croccanti straccetti di pollo fritto, scaglie di parmigiano e crostini di pane,serviti con l’originale salsa caesar)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('35','2','38','','','Pier 39','(insalata mista con gamberoni fritti, pompelmo rosa, finocchi e pomodorini)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('36','2','39','','','Classica','(Prosciutto cotto e mozzarella fior di latte con crema di pomodori secchi)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('36','2','40','','','Rustica','(Prosciutto crudo di montagna e mozzarella fior di latte con crema di olive nere)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('36','2','41','','','Caprese','(Pomodoro e mozzarella su letto di insalata romana, condito con pesto alla “genovese”)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('36','2','42','','','Cotoletta','(Tenera cotoletta di pollo con maionese su letto di insalata romana e pomodoro)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('37','2','43','','','Bresaola','(Pane integrale con bresaola IGP, rucola e scaglie di parmigiano)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('37','2','44','','','Tacchino','(Pane arabo -senza lievito- con fesa di tacchino, crema di formaggio e pomodoro)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('37','2','45','','','Il Panino del “Contadino” ','(Pane integrale con tris di verdure grigliate, pomodoro e pecorino)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('38','2','46','','','Norvegese','(Bagel con salmone norvegese, crema di formaggio, lime e pepe rosa)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('38','2','47','','','Americano','(Polpette di manzo, su di un letto di lattuga e pomodori, condito con salsa verde)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('38','2','48','','','Americano Veg','(Polpette di melanzane con provola affumicata, su di un letto di lattuga e pomodori, condito con maionese)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('39','2','49','','','Pizza e “Mortazza”',' (Pizza del forno con la mortadella di Bologna e salsa di pistacchi)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('39','2','50','','','Toast','(Prosciutto cotto e mozzarella filante)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('40','2','51','Medio','Large','I taglieri Salumi e Formaggi','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('41','2','52','','','Semifreddo Tiramisù','(Classica crema al tiramisù, con pan di spagna bagnato al caffè)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('41','2','53','','','Sufflè di cioccolato ','(Tortino con cuore morbido di cioccolato fondente)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('41','2','55','','','Cheesecake','(Gustoso semifreddo dalle note inconfondibili di crema di formaggio, con glassa di frutti di bosco)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('41','2','56','','','Semifreddo al Pistacchio','(Mousse di pistacchio decorata con granella di pistacchio)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('42','2','57','Medium','Large','Le spremute di frutta fresca','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('43','2','58','Medium','Large','Yougurt con frutta e cereali','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('44','2','59','Medium','Large','Macedonia di frutta di stagione','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('45','2','60','','','Classico','(Carota, mela e zenzero)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('45','2','61','','','ACE','(Arancia, carota e limone [zenzero])');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('45','2','62','','','Drenante','(Ananas, mela e finocchio)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('45','2','63','','','Depurativo','(Ananas, finocchio, limone [zenzero])');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('45','2','64','','','Vitaminico','(Kiwi, mela, zenzero)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('45','2','65','','','Bruciagrassi','(Pompelmo,limone,lime,ananas e zenzero)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('45','2','66','','','Pinzimonio','(Sedano,carota,finocchio,rape rosse condite con olio,sale e pepe)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('46','2','67','Calice','Bottiglia','Falanghina dei campi flegrei D.O.P','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('46','2','68','','Bottiglia','Falanghina dei campi flegrei D.O.P(375ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('46','2','69','Calice','Bottiglia','Vermentino Di Sardegna D.O.C','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('46','2','70','Calice','Bottiglia','Pecorino I.G.T','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('46','2','71','Calice','Bottiglia','Riflessi "Circeo" D.O.C','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('46','2','72','Calice','Bottiglia','Chardonnay(375ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('46','2','73','Calice','Bottiglia','Sauvignon Blanc "Fumaio" Castello Banfi','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('46','2','74','Calice','Bottiglia','Gewuzrtraminer','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('46','2','75','Calice','Bottiglia','Prosecco','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('46','2','76','Calice','Bottiglia','Merlot in purezza D.O.C','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('46','2','77','','Bottiglia','Merlot in purezza D.O.C(375ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('46','2','78','Calice','Bottiglia','Cabernet Sauvignon "Col di Sasso" Castello Banfi','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('46','2','79','Calice','Bottiglia','Chianti Classico D.O.C','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('46','2','80','Calice','Bottiglia','Chianti Riserva D.O.C','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('47','2','81','','','Nastro Azzurro(330ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('47','2','82','','','Ichnusa(330ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('47','2','83','','','Menebrea(330ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('47','2','84','','','IPA(330ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('47','2','85','','','Heineken(330ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('47','2','86','','','Ichnusa non filtrata (500ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('47','2','87','','','Peroni Riserva "Rossa"(500ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('47','2','88','','','Messina ai Cristalli di Sale (500ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('47','2','89','','','Weiss chiara','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('48','2','90','','','Acqua (500ml)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('48','2','91','','','Evian(1lt)','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('48','2','92','','','Fanta, Coca Cola, Sprite','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('48','2','93','','','Succhi di frutta naturali','(Pesca, ananas, mirtillo, ACE, pera)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('48','2','94','','','Thè freddo','(Limone,pesca)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('48','2','95','','','Chinotto','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('48','2','96','','','Acqua Tonica','(Classica e Lemon)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('48','2','97','','','Oransoda/Lemonsoda','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('48','2','98','','','Crodino/Campari Bitter','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('49','2','99','','','Amaro','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('49','2','100','','','Grappa','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('49','2','101','','','Rum/Whisky','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('49','2','102','','','Limoncello','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('49','2','103','','','Sambuca','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('50','2','104','','','Aperol/Campari Spritz','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('50','2','105','','','Alcolico','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('50','2','106','','','Analcolico','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('51','2','107','Classico','Large','Espresso',' ');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('51','2','108','Classico','','Deka','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('51','2','109','Classico','Large','Caffè Americano','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('51','2','110','Classico','Large','Caffè freddo','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('51','2','111','Classico','','Thè','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('51','2','112','Classico','','Tisana','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('51','2','113','Classico','Large','Cappuccino','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('51','2','114','Classico','Large','Caffèlatte/ Latte macchiato','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('51','2','115','Classico','','Marocchino','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('51','2','116','Classico','Large','Orzo','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('51','2','117','Classico','Large','Ginseng','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('51','2','118','Classico','','Cioccolata','(con panna + €0,50)');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('52','2','119','','','Brioche Artigianale','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('52','2','120','','','Ciambellone della nonna','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('52','2','121','','','Crostata di marmellata','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('52','2','122','','','Muffin','');
INSERT INTO DESCRIZIONE_ENTITY(STRUTTURA_ENTITY_ID_STRUTTURA_ENTITY,LINGUA_ENTITY_ID_LINGUA,MENU_ENTITY_ID_MENU,DIMENSIONE,DIMENSIONE_DUE,NOME,INGREDIENTE) VALUES('52','2','123','','','Torta del giorno','');


/*cinese*/


INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('经典小吃','','1');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('我们的纸袋装食品','','2');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('纸袋装炸鱼','','3');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('罗马菜肴','','4');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('当天的汤','','5');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('奶奶的好东西','','6');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('我们的菜单','','7');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('100％ 纯素沙拉','食材直接来源自农民..新鲜纯正','8');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('主厨沙拉','食材直接来源自农民..新鲜纯正','9');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('罗马恰巴塔','腊肠美食家的建议','10');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('低热量三明治','腊肠美食家的建议','11');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('美食家三明治（10分钟）','腊肠美食家的建议','12');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('简单…但很值得','腊肠美食家的建议','13');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('腊肠和奶酪拼盘','','14');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('单份甜点（无麸质）','','15');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('鲜榨果汁','','16');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('水果和谷物酸奶','','17');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('时令水果沙拉','','18');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('蔬菜果汁','完全天然...只有新鲜的水果和蔬菜，不加糖和冰','19');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('我们的酒窖','','20');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('啤酒','','21');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('饮料','','22');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('餐后酒','','23');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('鸡尾酒','','24');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('咖啡吧','','25');
INSERT INTO STRUTTURA_ENTITY (SOTTO_SEZIONE,SEZIONE,AGGREGANTE) VALUES ('甜点','','26');

/*
 * 1	53		经典小吃
2	54		我们的纸袋装食品
3	55		纸袋装炸鱼
4	56		罗马菜肴
5	57		当天的汤
6	58		奶奶的好东西
7	59		我们的菜单
8	60	食材直接来源自农民..新鲜纯正	100％ 纯素沙拉
9	61	食材直接来源自农民..新鲜纯正	主厨沙拉
10	62	腊肠美食家的建议	罗马恰巴塔
11	63	腊肠美食家的建议	低热量三明治
12	64	腊肠美食家的建议	美食家三明治（10分钟）
13	65	腊肠美食家的建议	简单…但很值得
14	66		腊肠和奶酪拼盘
15	67		单份甜点（无麸质）
16	68		鲜榨果汁
17	69		水果和谷物酸奶
18	70		时令水果沙拉
19	71	完全天然...只有新鲜的水果和蔬菜，不加糖和冰	蔬菜果汁
20	72		我们的酒窖
21	73		啤酒
22	74		饮料
23	75		餐后酒
24	76		鸡尾酒
25	77		咖啡吧
26	78		甜点
 */

